server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: devdojo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

