server:
  port: 8082

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: devdojo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

openapi:
  service:
    title: course-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: false
